### ISSUE TITLE
The software update caused all OWS setting to become the default value

### ISSUE THREAD

**Issue by yangym-IHEP** [lucarebuffi/OASYS-SRW#12]
Dear author,
I updated SRW and ShadowOUI last month. Unfortunately, a big problem had come up when I tried to re-open my saved ".ows" files. All the parameters that were set before are now the default values. The nodes' picture, text and link are correct, only parameters changed. What's more, the changes become irreversible after I save it. 
I checked the ".ows" file with text reader and found that the "node properties format was changed from the earlier "pickle" to now "literal". I am not sure if the problem was cause by SRW or ShadowOUI, but it persisted even after I updated today.

**Comment by lucarebuffi** [comment]
Dear user, that problem appeared years ago because of a bug of the python library "pickle", in the Anaconda distribution. It disappeared after release 3.7.1. It is impossible for me to help you without knowing in which operative system you are, how you installed the application and without a log of the runtime.

If you are on linux, open a terminal and type:

~/miniconda3/bin/python -m oasys.canvas -l4

open a workspace and then copy/paste the whole output into a text file and send it to me.

If you are on windows, open a Anaconda (Miniconda3) prompt and type:

python -m oasys.canvas -l4

and do the same procedure mentioned before.

If you are on Mac,  open a terminal and type:

/Applications/Oasys1.2.app/Content/MacOS/PythonApp -m oasys.canvas -l4

and do the same procedure mentioned before.

**Comment by yangym-IHEP** [comment]
Thanks for your reply. 

My operative system is windows. However, I installed OASYS by my own way because ANACONDA3 has been well deployed on my PC and I just didn't want to install another MINICONDA. So, I installed "xraylib" by `conda install xraylib` and OASYS packages by `pip install oasys1 oasys1-xxx`. Then I created a shortcut to excute `python -m oasys.canvas`. In fact, these are what you do in ".bat" installation file except using ANACONDA3 instead.

I opend OASYS with the command `python -m oasys.canvas -l4` and then opened my workspace. The output in anaconda prompt is as follows. 
[error.txt](https://github.com/oasys-kit/OASYS-SRW/files/5800478/error.txt)

**Comment by yangym-IHEP** [comment]
It seems that these is something wrong with "PyQt5". I checked my python packages with command `conda list`. 

> pyqt                      5.9.2            py37h6538335_4    conda-forge
pyqt5                     5.12.3                   pypi_0    pypi
pyqt5-sip                 12.8.1                   pypi_0    pypi
pyqtwebengine             5.15.1                   pypi_0    pypi

**Comment by lucarebuffi** [comment]
There is a reason why we did a separate environment, and your situation is why. Oasys needs to work on specific versions of the internal libraries, that we test continuously. Installation of the Add-ons (Shadow, SRW, etc..) must be done with the specific form within the application. We also use a minimal Anaconda to avoid filling the space on disk for no reasons. We do not provide support for non-standard installation: please install Oasys with its installation script.

**Comment by lucarebuffi** [comment]
FYI:

- PyQt5 >= 5.15
- PyQtWebEngine >= 5.12
- numpy >= 1.18
- scipy >= 1.4.1
- matplotlib >= 3.3.2

**Comment by yangym-IHEP** [comment]
Thank you for your kindly help. One quick question: how about I create a new environment by ANACONDA3 for OASYS only?

**Comment by lucarebuffi** [comment]
The installation script will do it for you. Please follow instructions!

https://github.com/oasys-kit/oasys-installation-scripts/wiki/Install-Oasys-in-Windows-10
