### ISSUE TITLE
intensity difference between the convolution and Monte Carlo ME simulation

### ISSUE THREAD

**Issue by yangfg-bsrf** [lucarebuffi/OASYS-SRW#6]
Hi, I tried to compared the partial coherence caculation by convolution and  by multiple electron simulation (script generated by the SRW Python Script ME, electrons number = 3000) in oasys-SRW. but the obvious intensity difference is found. would  you please help me check this?
![FLUX_ME](https://user-images.githubusercontent.com/41823786/68771398-e793b480-0662-11ea-9431-daece1fe495a.png)
In addition, the resolution and range factor do not work as we expected. I mean the range does not change as the factor reduces from 20 to 10, _**but the resolution changes**. And when I change the resolution factor, the range changes accordingly._
![image](https://user-images.githubusercontent.com/41823786/68773094-eadc6f80-0665-11ea-9af6-89d4d76791ac.png)
![image](https://user-images.githubusercontent.com/41823786/68773146-00ea3000-0666-11ea-95a6-563d6a9b0735.png)

**Comment by lucarebuffi** [comment]
Dear Fugui, SRW is not a tracing software. It is a wavefront propagation software. 
The fact that you find strange that the result of the Multi-Electron Convolution is different from the real Multi-Electron shows me that you don't have clear ideas about SRW. The M-E Convolution is accurate only right in front of the source, then is merely qualitative. According to the author of SRW, I shouldn't have given the possibility to see it after the source.
The real M-E is a long iterative procedure, that is supposed to be launched in large computing facilities, since you need several thousands of electrons sampled from the phase space of the electron beam, before being able to produce a result, depending of the degree of coherence of your beam. With how many electrons did you obtain the result you showed here?

Finally, if you use a "to Waist" propagator the range modificators are ignored. Use a "Quadratic" or "Quadratic Special" to see them work.

I strongly suggest to give a look to the material of the first oasys school, that you can access by clicking the dedicated button in the welcome screen of the application.
![Screen Shot 2019-11-13 at 11 03 42 AM](https://user-images.githubusercontent.com/6713598/68786394-53473480-0605-11ea-8b0f-52506e9ce6aa.png)
